# Generated by Django 5.0.2 on 2024-03-28 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ropa',
            name='img',
            field=models.ImageField(upload_to='ropaimagenes'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('ropa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='aplicacion.ropa')),
            ],
        ),
    ]
