# Generated by Django 5.0.2 on 2024-03-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_carro_itemcarro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarro',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
    ]
