# Generated by Django 5.0.2 on 2024-03-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_alter_itemcarro_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='productos',
            field=models.ManyToManyField(through='aplicacion.ItemCarro', to='aplicacion.ropa'),
        ),
        migrations.AlterField(
            model_name='itemcarro',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
