# Generated by Django 5.0.2 on 2024-03-28 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_carro_productos_alter_itemcarro_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarro',
            name='carro',
        ),
        migrations.RemoveField(
            model_name='itemcarro',
            name='producto',
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.ropa')),
            ],
        ),
        migrations.DeleteModel(
            name='Carro',
        ),
        migrations.DeleteModel(
            name='ItemCarro',
        ),
    ]
